name: PHP CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/php-ci.yaml
      - '**.php'
      - phpstan.neon
      - composer.lock
  pull_request:
    paths:
    - .github/workflows/php-ci.yaml
    - '**.php'
    - phpstan.neon
    - composer.lock

jobs:
  php-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Composer install
        uses: ramsey/composer-install@v1
        with:
          composer-options: --prefer-dist --ignore-platform-req=php

      - name: Run code-style checks (Rector)
        run: composer rector

      - name: Run code-style checks (ECS)
        run: composer ecs

      - name: Run PHPStan checks
        run: composer phpstan
